### ISSUE TITLE
Failed to pull image "registry.ng.bluemix.net/mionamespace2/dxen:v90": rpc error: code = Unknown desc = Error response from daemon: Get https://registry.ng.bluemix.net/v2/mionamespace2/dxen/manifests/v90: unauthorized: authentication required

### ISSUE THREAD

**Issue by matteofcorona** [digexp/DX.Kubernetes.IBM-Cloud#3]
Hi,
I am now facing the following problem whenever I try to import the PortalDeployment.yml after succesfully importing the PersistentVolumeClaim.yml (which is the step failing in the previous opened issue)

![image](https://user-images.githubusercontent.com/35602313/35431767-09abf9c8-027e-11e8-9c19-dde2f11c9945.png)

**Comment by georgefridrich** [comment]
Hi Matteo,
This looks like an auth issue.
If you get an "unauthorized: authentication required" or a "denied: requested access to the resource is denied" message, run the bx cr login command.
Let me know if that resolves.  Thanks.

**Comment by georgefridrich** [comment]
Hi Matteo,
I'm happy we have this resolved.  We'll modify our deployment yaml to include a mention about registry bluemix path as a variable.  We didn't consider that the path, e.g. registry.eu-gb.bluemix.net will be different overseas.  That is on us and we'll get that resolved asap.  Once done I will upload the new yaml and close this issue.  Thanks.

**Comment by georgefridrich** [comment]
Hi Matteo,
I'm going to close this issue now that it is resolved and the updated yaml is uploaded.  
I'll also update the readme to include this as a tip since you had to do it for your paid acct:
For paid accts. increase the quota limit beyond what the free trial provides:
https://console.bluemix.net/docs/services/Registry/registry_quota.html#registry_quota
